### ISSUE TITLE
Add Base91 compressed telemetry support

### ISSUE THREAD

**Issue by TJCoffey** [adriann0/npm-aprs-parser#16]
Add base91 compressed telemetry per the spec found here: http://he.fi/doc/aprs-base91-comment-telemetry.txt

I've started working on this over in my fork [here](https://github.com/TJCoffey/npm-aprs-parser/commit/4fe3f74582dd4c7d44a5cf0a5682327da114e869) but am unsure of the best way to proceed and could use some advice from those more familiar with this codebase. Here's where I'm at:

After rereading the spec, base91 TM can occur in the comment field of all three position report types (uncompressed, compressed, and MIC-E). I've broken the parser out into its own class instead of shoving it in the MIC-E position parsing. The commit referenced above just adds the new parser to the end of the parser list. When used like that, it ends up replacing the Position object in data with a Telemetry object, which is broken. For example, the previous parser:
```
N0CALL>APRS,qAR,IGATE:!6304.03NN02739.63E#PHG26303/Siilinjarvi|"p%T'.agff|
APRSMessage {
  from: Callsign { call: 'N0CALL' },
  to: Callsign { call: 'APRS' },
  via: [ Callsign { call: 'qAR' }, Callsign { call: 'IGATE' } ],
  raw:
   'N0CALL>APRS,qAR,IGATE:!6304.03NN02739.63E#PHG26303/Siilinjarvi|"p%T\'.agff|',
  data:
   Position {
     latitude: 63.067166666666665,
     longitude: 27.6605,
     symbol: 'N#',
     extension:
      PHG { heightFeet: 640, gaindB: 3, directivityDeg: 0, powerWatts: 4 },
     comment: '3/Siilinjarvi|"p%T\'.agff|',
     msgEnabled: false } }
```
With the new parser in the list:
```
APRSMessage {
  from: Callsign { call: 'N0CALL' },
  to: Callsign { call: 'APRS' },
  via: [ Callsign { call: 'qAR' }, Callsign { call: 'IGATE' } ],
  raw:
   'N0CALL>APRS,qAR,IGATE:!6304.03NN02739.63E#PHG26303/Siilinjarvi|"p%T\'.agff|',
  data:
   Telemetry { id: 170, analog: [ 415, 559, 5894, 6348 ], digital: [] } }
```
So that was dumb. When I look at this now, I feel like this telemetry makes most sense as a PositionExtension. Those parsers get called on position messages, and work by parsing the extension and removing the string from the comment. As far as I can tell, those parsers are only looking for one extension, though. Base91 can occur alongside some of the position extensions (see the packet above with PHG extension and base91 TM).

Any thoughts on the best place to integrate this?

**Comment by adriann0** [comment]
@TJCoffey I think we can just make telemetry another property inside of Position object, similar to "weather".

From implementation perspective it needs to be put in place where we try to parse extensions from comment (UncompressedPositionParserUtil.parseAltitudeWeatherAndExtension). Since this telemetry is delimited at both ends by the '|' it should be easy to find and remove from comment if parsing was successful. parseAltitudeWeatherAndExtension function can return many extensions but then these extensions need to be extracted and put into models (see callers of that function). One thing to note is this function is not called from MIC-E parser if I remember correctly - probably you will need to do something custom there (can MIC-E have extensions? if so maybe we can just call parseAltitudeWeatherAndExtension, if not then call base91 parser directly). You will need to create some helper to parse this base91 data. 

Take a look at WeatherParserUtils.js - your parser would probably be quite similar in terms of method signature and how it integrates with the rest of the code.

**Comment by TJCoffey** [comment]
Great. I think that's enough hints to get started. I hadn't looked at the weather extensions, but that definitely sounds like it's more similar than the PHG and other extensions I'd been looking at.

For MIC-E I can probably call the new parser in the same place that I had inserted the parse function in my old PR. That's the one place it was actually doing what it was supposed to. I'm not familiar enough with the MIC-E formats to know if they can contain the other extensions or if calling all the parsers will cause problems.

**Comment by klinquist** [comment]
Thank you for the contribution @TJCoffey!!
